EmployeeRegistration/Controllers/CompanyController.cs
using System;
using System.Web.Configuration;
using System.Web.Mvc;

using EmployeeRegistration.BusinessLayer.Interfaces;
using EmployeeRegistration.BusinessLayer.Models;
using EmployeeRegistration.BusinessLayer.Services;

namespace EmployeeRegistration.Controllers
{
    public class CompanyController : Controller
    {
        ICompanyService companyService;

        public CompanyController()
        {
            string connectionString = WebConfigurationManager.ConnectionStrings["EmployeeRegistration"].ConnectionString;
            companyService = new CompanyService(connectionString);
        }

        // GET: Company
        public ActionResult Index()
        {
            return View(companyService.GetAll());
        }

        // GET: Company/Create
        public ActionResult Create()
        {
            var company = new CompanyViewModel();

            return View("EntityForms/Create",company);
        }

        // POST: Company/Create
        [HttpPost]
        public ActionResult Create(CompanyViewModel company)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    companyService.AddCompany(company);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else return View(company);
        }

        // GET: Company/Edit/5
        public ActionResult Edit(int id)
        {
            CompanyViewModel company = companyService.Get(id);

            return View("EntityForms/Edit",company);
        }

        // POST: Company/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CompanyViewModel company)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    companyService.UpdateCompany(company);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                   
                    return View(ex.Message);
                }
            }
            else return View(company);
        }

        // GET: Company/Delete/5
        public ActionResult Delete(int id)
        {
            CompanyViewModel company = companyService.Get(id);

            return View("EntityForms/Delete",company);
        }

        // POST: Company/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    companyService.DeleteCompany(id);

                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    return View(ex.Message);
                }
            }
            else return View();
        }
    }
}

EmployeeRegistration/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Web.Configuration;
using System.Web.Mvc;

using EmployeeRegistration.BusinessLayer.Interfaces;
using EmployeeRegistration.BusinessLayer.Models;
using EmployeeRegistration.BusinessLayer.Services;

namespace EmployeeRegistration.Controllers
{
    public class EmployeeController : Controller
    {
        IEmployeeService employeeService;
        ICompanyService companyService;

        public EmployeeController()
        {
            string connectionString = WebConfigurationManager.ConnectionStrings["EmployeeRegistration"].ConnectionString;
            employeeService = new EmployeeService(connectionString);
            companyService = new CompanyService(connectionString);
        }

        // GET: Employee
        public ActionResult Index()
        {
            return View(employeeService.GetAll());
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            EmployeeViewModel employee = new EmployeeViewModel();
            TempData["Companies"] = companyService.GetAll();
            TempData["Positions"] = GetEmployeePostions();

            return View("EntityForms/Create",employee);
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    employeeService.AddEmployee(employee);

                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    return View(ex.Message);
                }
            }
            else return View(employee);
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                EmployeeViewModel employee = employeeService.Get(id);
                TempData["Companies"] = companyService.GetAll();
                TempData["Positions"] = GetEmployeePostions();

                return View("EntityForms/Edit", employee);
            }
            catch(Exception ex)
            {
                return View(ex.Message);
            }
        }

        // POST: Employee/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    employeeService.UpdateEmployee(employee);

                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    return View(ex.Message);
                }
            }
            else return View(employee);
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int id)
        {
            EmployeeViewModel employee = employeeService.Get(id);
            return View("EntityForms/Delete", employee);
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    employeeService.DeleteEmployee(id);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View(ex.Message);
                }
            }
            else return View();
        }

        public List<string> GetEmployeePostions()
        {
            return new List<string> {
                 "Разработчик",
                "Тестировщик",
                "Бизнес-аналитик",
                "Менеджер"
                };
        }
    }
}

EmployeeRegistration/Controllers/HomeController.cs
using EmployeeRegistration.BusinessLayer.Interfaces;
using EmployeeRegistration.BusinessLayer.Services;
using System.Web.Configuration;
using System.Web.Mvc;

namespace EmployeeRegistration.Controllers
{
    public class HomeController : Controller
    {
        IEmployeeService employeeService;
        ICompanyService companyService;

        public HomeController()
        {
            string connectionString = WebConfigurationManager.ConnectionStrings["EmployeeRegistration"].ConnectionString;
            companyService = new CompanyService(connectionString);
            employeeService = new EmployeeService(connectionString);
        }

        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Employees()
        {
            return PartialView("Partial/EmployeesPartial", employeeService.GetAll());
        }

        public PartialViewResult Companies()
        {
            return PartialView("Partial/CompaniesPartial", companyService.GetAll());
        }
    }
}

EmployeeRegistration/Views/Company/EntityForms/Create.cshtml
@model EmployeeRegistration.BusinessLayer.Models.CompanyViewModel

@{
    ViewBag.Title = "Добавить компанию";
}

    <hr />
<h3>Добавить компанию</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.CompanySize)
    <div class="form-group">
        @Html.LabelFor(model => model.CompanySize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Label(Model.CompanySize.ToString(), new { @class = "form-control-static"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LegalForm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LegalForm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LegalForm, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ActivityType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ActivityType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ActivityType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Добавить" class="btn btn-primary" />
            @Html.ActionLink("Отмена", "Index",null, new { @class ="btn btn-default"})
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeRegistration/Views/Company/EntityForms/Delete.cshtml
@model EmployeeRegistration.BusinessLayer.Models.CompanyViewModel

@{
    ViewBag.Title = "Удаление компании";
}

<hr />
<h3>Удаление компании</h3>
<h5>Вы действительно хотите удалить компанию?</h5>
<p class="text-danger">При удалении компании удаляются все сотрудники это компании</p>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>
       <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanySize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanySize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LegalForm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LegalForm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivityType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityType)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="col-md-offset-2 form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" />
            @Html.ActionLink("Отмена", "Index",null, new { @class = "btn btn-default" })
        </div>
    }
</div>

EmployeeRegistration/Views/Company/EntityForms/Edit.cshtml
@model EmployeeRegistration.BusinessLayer.Models.CompanyViewModel

@{
    ViewBag.Title = "Изменение данных компании";
}

    <hr />
 <h3>Изменение данных компании</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CompanyId)
    <div class="form-group">
        @Html.LabelFor(model => model.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Label(Model.CompanyId.ToString(), new { @class = "form-control-static" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.CompanySize)
    <div class="form-group">
        @Html.LabelFor(model => model.CompanySize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Label(Model.CompanySize.ToString(), new { @class = "form-control-static" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LegalForm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LegalForm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LegalForm, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ActivityType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ActivityType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ActivityType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeRegistration/Views/Company/Index.cshtml
@model IEnumerable<EmployeeRegistration.BusinessLayer.Models.CompanyViewModel>

@{
    ViewBag.Title = "Список компаний";
}

<hr />
<h4>Список компаний</h4>
<p>
    <div class="form-group">
        <div class="input-group">
            @Html.ActionLink("Добавить компанию", "Create", null, new { @class = "btn btn-success input-group-addon" })
            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
            <input type="text" id="Search" placeholder="Поиск" class="form-control" />

        </div>
    </div>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanySize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LegalForm)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActivityType)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="Search">
            <td>
                @Html.DisplayFor(modelItem => item.CompanyId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanySize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LegalForm)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActivityType)
            </td>
            <td>
                @Html.ActionLink("Изменить", "Edit", new { id = item.CompanyId }, new { @class = "btn btn-sm btn-default" })
                @Html.ActionLink("Удалить", "Delete", new { id = item.CompanyId }, new { @class = "btn btn-sm btn-danger" })
            </td>
        </tr>
    }

</table>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        function Contains(text_one, text_two) {
            if (text_one.indexOf(text_two) != -1)
                return true;
        }
        $("#Search").keyup(function () {
            var searchText = $("#Search").val().toLocaleLowerCase();
            $(".Search").each(function () {
                if (!Contains($(this).text().toLocaleLowerCase(), searchText)) {
                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            })
        })
    })
</script>

EmployeeRegistration/Views/Employee/EntityForms/Create.cshtml
@model EmployeeRegistration.BusinessLayer.Models.EmployeeViewModel

@{
    ViewBag.Title = "Добавление работника";
}

    <hr />
<h3>Добавление работника</h3>
@{
    TempData.Keep("Positions");
    var positions = (List<string>)TempData["Positions"];

    TempData.Keep("Companies");
    var companies = (System.Collections.ObjectModel.ObservableCollection<EmployeeRegistration.BusinessLayer.Models.CompanyViewModel>)TempData["Companies"];

}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmploymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmploymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmploymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Position, new SelectList(positions), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyId, new SelectList(companies, "CompanyId", "CompanyName"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeRegistration/Views/Employee/EntityForms/Delete.cshtml
@model EmployeeRegistration.BusinessLayer.Models.EmployeeViewModel

@{
    ViewBag.Title = "Удаление работника";
}

    <hr />
<h3>Удаление работника</h3>
<h5>Вы действительно хотите удалить этого работника?</h5>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmploymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmploymentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()


        <div class="col-md-offset-2 form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" />
            @Html.ActionLink("Отмена", "Index",null, new { @class ="btn btn-default"})
        </div>
    }
</div>

EmployeeRegistration/Views/Employee/EntityForms/Edit.cshtml
@model EmployeeRegistration.BusinessLayer.Models.EmployeeViewModel

@{
    ViewBag.Title = "Изменение данных работника";
}

    <hr />
<h3>Изменение данных работника</h3>
@{
    TempData.Keep("Positions");
    var positions = (List<string>)TempData["Positions"];

    TempData.Keep("Companies");
    var companies = (System.Collections.ObjectModel.ObservableCollection<EmployeeRegistration.BusinessLayer.Models.CompanyViewModel>)TempData["Companies"];
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeId)
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label(Model.EmployeeId.ToString(),new { @class = "form-control-static" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmploymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmploymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmploymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Position, new SelectList(positions,Model.Position), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyId, new SelectList(companies, "CompanyId", "CompanyName",Model.Company), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                @Html.ActionLink("Отмена", "Index",null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeRegistration/Views/Employee/Index.cshtml
@model IEnumerable<EmployeeRegistration.BusinessLayer.Models.EmployeeViewModel>

@{
    ViewBag.Title = "Список работников";
}

<hr />
<h4>Список работников</h4>

<p>
    <div class="form-group">
        <div class="input-group">
            @Html.ActionLink("Добавить работника", "Create", null, new { @class = "btn btn-success input-group-addon" })
            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
            <input type="text" id="Search" placeholder="Поиск" class="form-control" />

        </div>
    </div>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MiddleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmploymentDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="Search">
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmploymentDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company.CompanyName)
            </td>
            <td>
                @Html.ActionLink("Изменить", "Edit", new { id = item.EmployeeId }, new { @class = "btn btn-sm btn-default" })
                @Html.ActionLink("Удалить", "Delete", new { id = item.EmployeeId }, new { @class = "btn btn-sm btn-danger" })
            </td>
        </tr>
    }
</table>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        function Contains(text_one, text_two) {
            if (text_one.indexOf(text_two) != -1)
                return true;
        }
        $("#Search").keyup(function () {
            var searchText = $("#Search").val().toLocaleLowerCase();
            $(".Search").each(function () {
                if (!Contains($(this).text().toLocaleLowerCase(), searchText)) {
                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            })
        })
    })
</script>

EmployeeRegistration/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная страница";
}


<hr />
<h4>Список работников</h4>
@Html.Action("Employees")
<hr />
<h4>Список компаний</h4>
@Html.Action("Companies")

EmployeeRegistration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Главное меню", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Работники", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Компании", "Index", "Company")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>